name: "Deploy Specific Tag to Test Cluster"
run-name: "Deploy Specific Tag to Test Cluster"
on:
  push:
    branches:
      - master

env:
  TEST_SERVICE: "kindred-data-service"
  TAG_TAG: "latest-prod"

jobs:
  build:
    runs-on:
      labels: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: 'Build'
        run: |
          mvn compile
          mvn package
  test:
    runs-on:
      labels: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: 'Build'
        run: |
          mvn test
  deploy:
    runs-on:
      labels: [self-hosted, linux]
    steps:
      - name: 'Deploy'
        run: |
          cp -rf target/spring-boot-redis-example-0.0.1-SNAPSHOT.jar  /home/marius

